[formatting]
indent_string = "\t"
align_entries = true
column_width  = 120

[[rule]]
include = ["**/Cargo.toml"]
keys    = ["dependencies", "workspace"]

[rule.formatting]
reorder_keys          = true
reorder_arrays        = true
reorder_inline_tables = true
