[workspace]

members = ["zutil-legacy"]
resolver = "2"

[workspace.dependencies]

# Workspace members
zutil-legacy = { path = "zutil-legacy" }

arrayref = "0.3.6"
ascii = "1.0.0"
derive_more = "0.99.14"
eframe = { git = "https://github.com/emilk/egui", rev = "7c5a2d60" }
either = "1.6.1"
futures = "0.3.15"
int-conv = "0.1.4"
log = "0.4.14"
native-dialog = "0.5.5"
ref-cast = "1.0.6"
sealed = "0.3.0"
serde = "1.0.120"
thiserror = "1.0.23"

[workspace.lints]

# No unsafe allowed in this crate
rust.unsafe_code = "forbid"

# Must use `expect` instead of `unwrap`
clippy.unwrap_used = "forbid"
