[workspace]

members = [
	"tests/zutil-inheritance-derive",
	"zutil-async-loadable",
	"zutil-cloned",
	"zutil-inheritance",
	"zutil-inheritance-macros",
	"zutil-logger",
]
resolver = "2"

[workspace.package]
authors    = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
edition    = "2024"
license    = "MIT OR Apache-2.0"
repository = "https://github.com/zenithsiz/zutil"

[workspace.dependencies]


# Workspace members
# TODO: Do we need to specify the version here?
zutil-inheritance        = { path = "zutil-inheritance", version = "0.1.0" }
zutil-inheritance-macros = { path = "zutil-inheritance-macros", version = "0.1.0" }

app-error          = "0.1.1"
convert_case       = "0.11.0"
futures            = "0.3.32"
itertools          = "0.14.0"
mappable-rc        = "0.1.1"
parking_lot        = "0.12.5"
pin-project        = "1.1.11"
proc-macro2        = "1.0.106"
quote              = "1.0.45"
stable_deref_trait = "1.2.1"
strum              = "0.28.0"
syn                = "2.0.117"
tokio              = "1.52.1"
tracing            = "0.1.44"
tracing-subscriber = "0.3.23"
trybuild           = "1.0.116"
yoke               = "0.8.2"

[workspace.lints]


clippy.nursery  = { level = "warn", priority = -1 }
clippy.pedantic = { level = "warn", priority = -1 }

# Must use `expect` instead of `unwrap`
clippy.unwrap_used = "forbid"

# Improve unsafe usage
clippy.multiple_unsafe_ops_per_block = "warn"
clippy.undocumented_unsafe_blocks    = "warn"

# Style
clippy.match_bool           = "allow"
clippy.option_if_let_else   = "allow"
clippy.single_match_else    = "allow"
clippy.tabs_in_doc_comments = "allow"

# Misc.
clippy.missing_errors_doc     = "allow"
clippy.similar_names          = "allow"
clippy.struct_excessive_bools = "allow"

# False positives
clippy.significant_drop_tightening = "allow"
