[package]
name = "zutil-async-loadable"
version = "0.1.0"
edition = "2024"

[dependencies]

# Workspace
zutil-app-error = { workspace = true }

parking_lot = { workspace = true, features = ["arc_lock", "send_guard"] }
pin-project = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }

[dev-dependencies]

futures = { workspace = true }
tokio = { workspace = true, features = ["macros"] }


[lints]
workspace = true
