[package]
name        = "zutil-logger"
version     = "0.1.1"
description = "`tracing` logger"
edition     = { workspace = true }
authors     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]

itertools          = { workspace = true }
tracing            = { features = ["log"], workspace = true }
tracing-subscriber = { features = ["env-filter"], workspace = true }

[lints]
workspace = true
